spring:
  application:
    name: ISHOP
# config POSTGRES Database
  datasource:
    url: jdbc:postgresql://localhost:5432/ishop-db
    username: postgres
    password: supermatra
    driver-class-name: org.postgresql.Driver

# config JPA DDL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
# email smtp setup
  mail:
    host: smtp.gmail.com
    port: 587
    username: cheysomatra@gmail.com
    password: qzpxnzwjpgvspasr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp

# Config Swagger
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /doc
    enabled: true

# Generate file
file:
  target: uploads/
  media-url: http://localhost:8080/files

# Config key JWT
jwt:
  private-key: classpath:keys/private_key.pem
  public-key: classpath:keys/public_key.pem
  access-token:
    expire: 180000 # 3s = 3000ms
  refresh-token:
    expire: 3000000 # 3min = 300000ms

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
    hibernate:
      SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE